# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = waybar & hypridle & hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- bitwarden-desktop
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- Telegram -startintray

# Enable only on laptops
# Enable first timer 
# systemctl --user daemon-reload
# systemctl --user enable battery-monitor.timer
# systemctl --user start battery-monitor.timer

# exec-once = systemctl --user start battery-monitor.timer
