source = ~/.config/theme/tokyo-night/hyprlock.conf

$font = JetBrainsMono Nerd Font 

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.config/backgrounds/wp8438092-tokyo-4k-wallpapers.jpg
    blur_passes = 2
    color = $color
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 4

    inner_color = $inner_color
    outer_color = $outher_color
    check_color = $check_color

    font_color = $font_color
    fade_on_empty = false
    rounding = 4

    font_family = $font
    placeholder_text = Input password...
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 0
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = Keyboard layout: $LAYOUT
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 30, 10
    halign = left 
    valign = bottom
}

