# Image origin: https://github.com/orangci/walls-catppuccin-mocha
wallpaper {
    monitor = 
    path = ~/.config/backgrounds/wp8438092-tokyo-4k-wallpapers.jpg
    fit_mode = cover
}

splash = false

