# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
  name = pavucontrol-float-center
  size = (monitor_w*0.5) (monitor_h*0.8)
  float = true
  match:class = ^(org.pulseaudio.pavucontrol)$
  center = true
}

windowrule {
  name = kitty-tui-float-center
  size = (monitor_w*0.5) (monitor_h*0.8)

  float = true
  match:class = ^(kitty.impala|kitty.bluetui|kitty.btop|kitty.nmtui|kitty.wlctl)$
  center = true
}
windowrule {
  name = nwg-look-float-center
  size = (monitor_w*0.5) (monitor_h*0.8)

  float = true 
  match:class = ^(nwg-look)$
  center = true
}
windowrule {
  name = protonvpn-app-float-center
  size = (monitor_w*0.3) (monitor_h*0.8)

  float = true 
  match:class = ^(protonvpn-app)$
  center = true
}
windowrule {
  name = localsend-float-center
  size = (monitor_w*0.5) (monitor_h*0.8)

  float = true
  match:class = ^(Share|localsend)$
  center = true
}

windowrule {
  name = calculator-float-center
  size = (monitor_w*0.3) (monitor_h*0.8)

  float = true
  match:class = ^(org.gnome.Calculator)$
  center = true
}

